project:
  type: website

website:
  title: "Xingrui's Project"
  sidebar:
    contents:
      - href: Introduction.qmd
        text: Introduction
      - href: index.qmd
        text: About me
      - href: Code.qmd
        text: Code
      - tab: Data
        href: DataMain.qmd  # This makes the "Data" tab clickable
        contents:
          - href: Data.qmd
            text: Data
          - href: Data Gathering.qmd
            text: Data Gathering
          - href: Data Exploration.qmd
            text: Data Exploration
          - href: Data Cleaning R.ipynb
            text: Data Cleaning in R
          - href: Data Cleaning Python.qmd
            text: Data Cleaning in python
      - href: Clustering.qmd
        text: Clustering
      - href: NB.qmd
        text: Naïve Bayes
      - href: Dimensionality Reduction.qmd
        text: Dimensionality Reduction
      - href: Decision Trees.qmd
        text: Decision Trees
      - href: Conclusions.qmd
        text: Conclusions

format:
  html:
    theme: cosmo
    toc: true
