---
title: "Data Section"
format: html
---


This is a link to data in GitHub [Click here](https://github.com/anly501/dsan-5000-project-FroomeBeibei79/tree/main/data)


# Data 

This project will primarily focus on driver behavior analysis. Specifically, we will dive into a different set of groups to learn about what kind of groups with specific characteristics have higher fatality rates in passenger vehicle accidents and look for possible reasons behind them.

What kind of data is helpful in terms of driver behavior analysis? 

Basically, driver behavior is people driving cars. There will be different groups like gender, young drivers, older drivers, etc. We will elaborate on different groups one after another.
We can also acquire analysis from the vehicle side, that is, how a vehicle behaves while the vehicle is in operation. However, data acquisition is hard to get as, nowadays, car motion data from individual drivers are considered private information and thus cannot be accessed by the public. We will leave this part for now and probably come back for more in the future.





## Driver Side

### Gender

Gender is a significant factor that has an impact on driver behavior. When it comes to fatal injury odds in passenger vehicle accidents, "the fatal injury odds for females were lower than males." [(p21)](https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/813513)

### Young driver

Another publication focus on [young driver](https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/813492) affect driver behavior analysis, as statistics state that "The rate of drivers involved in fatal traffic crashes per 100,000 licensed drivers for young female drivers was 25.51 in 2021. For young male drivers in 2021 the involvement rate was 60.28, more than twice that of young female drivers. " (U.S. Department of Transportation, National Highway Traffic Safety Administration. (2022). Traffic Safety Facts 2021 Data (Report No. 813492))

